### ISSUE TITLE
Including one proto file into another does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Arshia001/FSharp.GrpcCodeGenerator#13]
Having this project
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarnOn>3390;$(WarnOn)</WarnOn>
    </PropertyGroup>

    <ItemGroup>
        <Protobuf Include="proto/unpacker.proto" GrpcServices="Both"/>
        <Protobuf Include="proto/task.proto"/>
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Grpc-FSharp.Core" Version="0.1.1" />
      <PackageReference Include="Grpc-FSharp.Tools" Version="0.1.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
</Project>
```
I've got the following errors
```
0>/Users/vaskir/.nuget/packages/grpc-fsharp.tools/0.1.1/tools/macosx_x64/protoc --fsharp_out=obj/Debug/net5.0/proto/unpacker.proto --proto_path=/Users/vaskir/.nuget/packages/grpc-fsharp.tools/0.1.1/build/native/include --proto_path=. --dependency_out=obj/Debug/net5.0/dfe805b7589f203f_unpacker.protodep --error_format=msvs proto/unpacker.proto
0>task.proto: Error  : File not found.
0>proto/unpacker.proto(6,1): Error  : Import "task.proto" was not found or had errors.
0>proto/unpacker.proto(13,3): Error  : "Task" is not defined.
0>proto/unpacker.proto(17,3): Error  : "Task" is not defined.
0>------- Finished building project: Proto. Succeeded: False. Errors: 4. Warnings: 0
```
The editor shows the errors as well

![image](https://user-images.githubusercontent.com/873919/133999696-feaa7457-eb91-4958-9b4d-1a42b90970fb.png)

**Comment by Arshia001** [comment]
Hi!

There are 2 aspects to including `.proto` files:

* The protoc tool uses information from an included file to understand the types the proto code is going to interact with. This is handled by adding 'Import Path's.
* The proto code must be 'compiled' to F#. This happens when you add a `<Protobuf>` element in your project files.

To import a proto file, you need to make it available in the proto_paths the protoc tool scans. As you can see in the output, it's scanning `/Users/vaskir/.nuget/packages/grpc-fsharp.tools/0.1.1/build/native/include` which is the directory the 'standard' proto files from Google live inside (which are packaged with the Nuget library), and `.`, which is the project directory. You have your proto files in `./proto`, which is why you're getting the error.

To fix this, you have two ways:
* Change the line in your proto file to `import proto/task.proto'.
* Add the proto directory as an additional import path. You can do this by adding the following to your project file:
```xml
  <PropertyGroup>
    <Protobuf_AdditionalImportsPath>
      ./proto
    </Protobuf_AdditionalImportsPath>
  </PropertyGroup>
```

Also, note that you can simply import other proto files from other projects without ever needing to compile those into your project's binaries. To do this, you'd simply add the path of the proto files from other projects to your project file as an import path. This is how we use it:

```xml
  <PropertyGroup>
    <Protobuf_AdditionalImportsPath>
      ../API.Common; <!-- notice the ; is used to separate values -->
      ../../Base/Protobuf
    </Protobuf_AdditionalImportsPath>
  </PropertyGroup>
```

Now, you could say this is a flaw and the tool should handle relative paths as well. However, the MSBuild section of this project is mostly a copy-paste of the code in the C# protobuf libraries, which are officially supported. If they did it like this, I'm sure they had their reasons.
